# Stage 1: Build the application
FROM maven:3.9-eclipse-termurin-21 AS builder

# Set the working directory inside the container
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

#Copy the source code and build the application
COPY src ./src
RUN mvn clean package --DskipTests


# Stage 2: Run the application
FROM gcr.io/distroless/java17-debian12:nonroot

WORKDIR /app

#Copy the built JAR file from the previous stage
COPY --from=builder /app/target/TaskManager-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8080 for the Spring Boot app
EXPOSE 8080

# Set environment variables for MySQL connection (Optional, use Docker Compose instead)
ENV SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/taskdb?useSSL=false&allowPublicKeyRetrieval=true
ENV SPRING_DATASOURCE_USERNAME=root
ENV SPRING_DATASOURCE_PASSWORD=Rishi@2001
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=update


# Run the application
USER nonroot
ENTRYPOINT ["java", "-jar", "app.jar"]
